<?php

	return array(
		// Languages that are allowed in routes
		// Other prefixes will show a 404 page (if route is not defined)
		'languagesAllowed' 		=> array ('en','es'),

		// Take the browser language if it's not defined in the route? 
		// If false, system will take app.php locale attribute 
		'useBrowserLanguage'	=> true,

		// Specify custom class for language bar unordered list
		'languageBarClass' => 'laravel_language_chooser',
		
		// List of all languages supported
		// Feel free to add a new one
		'supportedLanguages' => array(
			"ab" => "Abkhaz",
			"aa" => "Afar",
			"af" => "Afrikaans",
			"ak" => "Akan",
			"sq" => "Albanian",
			"am" => "Amharic",
			"ar" => "Arabic",
			"an" => "Aragonese",
			"hy" => "Armenian",
			"as" => "Assamese",
			"av" => "Avaric",
			"ae" => "Avestan",
			"ay" => "Aymara",
			"az" => "Azerbaijani",
			"bm" => "Bambara",
			"ba" => "Bashkir",
			"eu" => "Basque",
			"be" => "Belarusian",
			"bn" => "Bengali",
			"bh" => "Bihari",
			"bi" => "Bislama",
			"bs" => "Bosnian",
			"br" => "Breton",
			"bg" => "Bulgarian",
			"my" => "Burmese",
			"ca" => "Catalan",
			"ch" => "Chamorro",
			"ce" => "Chechen",
			"zh" => "Chinese",
			"cv" => "Chuvash",
			"kw" => "Cornish",
			"co" => "Corsican",
			"cr" => "Cree",
			"hr" => "Croatian",
			"cs" => "Czech",
			"da" => "Danish",
			"nl" => "Dutch",
			"dz" => "Dzongkha",
			"en" => "English",
			"eo" => "Esperanto",
			"et" => "Estonian",
			"ee" => "Ewe",
			"fo" => "Faroese",
			"fj" => "Fijian",
			"fi" => "Finnish",
			"fr" => "French",
			"gl" => "Galician",
			"lg" => "Ganda",
			"ka" => "Georgian",
			"de" => "German",
			"el" => "Greek, Modern",
			"gn" => "Guaraní",
			"gu" => "Gujarati",
			"ha" => "Hausa",
			"he" => "Hebrew (modern)",
			"hz" => "Herero",
			"hi" => "Hindi",
			"ho" => "Hiri Motu",
			"hu" => "Hungarian",
			"is" => "Icelandic",
			"io" => "Ido",
			"ig" => "Igbo",
			"id" => "Indonesian",
			"iu" => "Inuktitut",
			"ik" => "Inupiaq",
			"ga" => "Irish",
			"it" => "Italian",
			"ja" => "Japanese",
			"jv" => "Javanese",
			"kr" => "Kanuri",
			"ks" => "Kashmiri",
			"kk" => "Kazakh",
			"km" => "Khmer",
			"ki" => "Kikuyu",
			"rw" => "Kinyarwanda",
			"rn" => "Kirundi",
			"kv" => "Komi",
			"kg" => "Kongo",
			"ko" => "Korean",
			"ku" => "Kurdish",
			"ky" => "Kyrgyz",
			"lo" => "Lao",
			"la" => "Latin",
			"lv" => "Latvian",
			"ln" => "Lingala",
			"lt" => "Lithuanian",
			"lu" => "Luba-Katanga",
			"mk" => "Macedonian",
			"mg" => "Malagasy",
			"ms" => "Malay",
			"ml" => "Malayalam",
			"mt" => "Maltese",
			"gv" => "Manx",
			"mh" => "Marshallese",
			"mn" => "Mongolian",
			"mi" => "Māori",
			"na" => "Nauru",
			"ng" => "Ndonga",
			"ne" => "Nepali",
			"nd" => "North Ndebele",
			"se" => "Northern Sami",
			"no" => "Norwegian",
			"ii" => "Nuosu",
			"oc" => "Occitan",
			"or" => "Oriya",
			"om" => "Oromo",
			"fa" => "Persian",
			"pl" => "Polish",
			"pt" => "Portuguese",
			"qu" => "Quechua",
			"ro" => "Romanian",
			"rm" => "Romansh",
			"ru" => "Russian",
			"sm" => "Samoan",
			"sg" => "Sango",
			"sc" => "Sardinian",
			"sr" => "Serbian",
			"sn" => "Shona",
			"sd" => "Sindhi",
			"sk" => "Slovak",
			"sl" => "Slovene",
			"so" => "Somali",
			"nr" => "South Ndebele",
			"st" => "Southern Sotho",
			"es" => "Spanish",
			"su" => "Sundanese",
			"sw" => "Swahili",
			"ss" => "Swati",
			"sv" => "Swedish",
			"tl" => "Tagalog",
			"ty" => "Tahitian",
			"tg" => "Tajik",
			"ta" => "Tamil",
			"tt" => "Tatar",
			"te" => "Telugu",
			"th" => "Thai",
			"ti" => "Tigrinya",
			"ts" => "Tsonga",
			"tn" => "Tswana",
			"tr" => "Turkish",
			"tk" => "Turkmen",
			"tw" => "Twi",
			"uk" => "Ukrainian",
			"ur" => "Urdu",
			"uz" => "Uzbek",
			"ve" => "Venda",
			"vi" => "Vietnamese",
			"vo" => "Volapük",
			"wa" => "Walloon",
			"cy" => "Welsh",
			"fy" => "Western Frisian",
			"wo" => "Wolof",
			"xh" => "Xhosa",
			"yi" => "Yiddish",
			"yo" => "Yoruba",
			"za" => "Zhuang, Chuang",
			"zu" => "Zulu"
		),


	);