<?php

return [
    // Uncomment the languages that your site supports - or add new ones.
    // These are sorted by the native name, which is the order you might show them in a language selector.
    // Regional languages are sorted by their base language, so "British English" sorts as "English, British"
    'supportedLocales' => [
        //'aa'          => ['name' => 'Afar',                 'script' => 'Latn', 'native' => 'Qafar', 'regional' => 'aa_ER'],
        //'ab'          => ['name' => 'Abkhazian',            'script' => 'Cyrl', 'native' => 'Аҧсуа', 'regional' => ''],
        //'ace'         => ['name' => 'Achinese',             'script' => 'Latn', 'native' => 'Aceh', 'regional' => ''],
        //'ady'         => ['name' => 'Adyghe',               'script' => 'Cyrl', 'native' => 'адыгэбзэ', 'regional' => ''],
        //'ae'          => ['name' => 'Avestan',              'script' => 'Latn', 'native' => 'avesta', 'regional' => ''],
        //'af'          => ['name' => 'Afrikaans',            'script' => 'Latn', 'native' => 'Afrikaans', 'regional' => 'af_ZA'],
        //'agq'         => ['name' => 'Aghem',                'script' => 'Latn', 'native' => 'Aghem', 'regional' => ''],
        //'ak'          => ['name' => 'Akan',                 'script' => 'Latn', 'native' => 'Akan', 'regional' => 'ak_GH'],
        //'ale'         => ['name' => 'Aleut',                'script' => 'Latn', 'native' => 'Unangax tunuu', 'regional' => ''],
        //'am'          => ['name' => 'Amharic',              'script' => 'Ethi', 'native' => 'አማርኛ', 'regional' => 'am_ET'],
        //'an'          => ['name' => 'Aragonese',            'script' => 'Latn', 'native' => 'aragonés', 'regional' => 'an_ES'],
        //'ang'         => ['name' => 'Old English',          'script' => 'Runr', 'native' => 'Old English', 'regional' => ''],
        //'ar'          => ['name' => 'Arabic',               'script' => 'Arab', 'native' => 'العربية', 'regional' => 'ar_AE'],
        //'as'          => ['name' => 'Assamese',             'script' => 'Beng', 'native' => 'অসমীয়া', 'regional' => 'as_IN'],
        //'asa'         => ['name' => 'Kipare',               'script' => 'Latn', 'native' => 'Kipare', 'regional' => ''],
        //'av'          => ['name' => 'Avaric',               'script' => 'Cyrl', 'native' => 'авар мацӀ', 'regional' => ''],
        //'ay'          => ['name' => 'Aymara',               'script' => 'Latn', 'native' => 'aymar aru', 'regional' => 'ay_PE'],
        //'az'          => ['name' => 'Azerbaijani (Latin)',  'script' => 'Latn', 'native' => 'azərbaycanca', 'regional' => 'az_AZ'],
        //'az-Cyrl'     => ['name' => 'Azerbaijani (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Азәрбајҹан', 'regional' => 'uz_UZ'],
        //'ba'          => ['name' => 'Bashkir',              'script' => 'Cyrl', 'native' => 'башҡорт теле', 'regional' => ''],
        //'bas'         => ['name' => 'Basa',                 'script' => 'Latn', 'native' => 'Ɓàsàa', 'regional' => ''],
        //'be'          => ['name' => 'Belarusian',           'script' => 'Cyrl', 'native' => 'беларуская', 'regional' => 'be_BY'],
        //'bem'         => ['name' => 'Bemba',                'script' => 'Latn', 'native' => 'Ichibemba', 'regional' => 'bem_ZM'],
        //'bez'         => ['name' => 'Bena',                 'script' => 'Latn', 'native' => 'Hibena', 'regional' => ''],
        //'bg'          => ['name' => 'Bulgarian',            'script' => 'Cyrl', 'native' => 'български', 'regional' => 'bg_BG'],
        //'bh'          => ['name' => 'Bihari',               'script' => 'Latn', 'native' => 'Bihari', 'regional' => ''],
        //'bi'          => ['name' => 'Bislama',              'script' => 'Latn', 'native' => 'Bislama', 'regional' => ''],
        //'bm'          => ['name' => 'Bambara',              'script' => 'Latn', 'native' => 'bamanakan', 'regional' => ''],
        //'bn'          => ['name' => 'Bengali',              'script' => 'Beng', 'native' => 'বাংলা', 'regional' => 'bn_BD'],
        //'bo'          => ['name' => 'Tibetan',              'script' => 'Tibt', 'native' => 'པོད་སྐད་', 'regional' => 'bo_IN'],
        //'br'          => ['name' => 'Breton',               'script' => 'Latn', 'native' => 'brezhoneg', 'regional' => 'br_FR'],
        //'bra'         => ['name' => 'Braj',                 'script' => 'Deva', 'native' => 'ब्रज भाषा', 'regional' => ''],
        //'brx'         => ['name' => 'Bodo',                 'script' => 'Deva', 'native' => 'बड़ो', 'regional' => 'brx_IN'],
        //'bs'          => ['name' => 'Bosnian',              'script' => 'Latn', 'native' => 'bosanski', 'regional' => 'bs_BA'],
        //'byn'         => ['name' => 'Blin',                 'script' => 'Ethi', 'native' => 'ብሊን', 'regional' => 'byn_ER'],
        //'ca'          => ['name' => 'Catalan',              'script' => 'Latn', 'native' => 'català', 'regional' => 'ca_ES'],
        //'ca-valencia' => ['name' => 'Valencian',            'script' => 'Latn', 'native' => 'valencià', 'regional' => ''],
        //'cch'         => ['name' => 'Atsam',                'script' => 'Latn', 'native' => 'Atsam', 'regional' => ''],
        //'ce'          => ['name' => 'Chechen',              'script' => 'Cyrl', 'native' => 'нохчийн мотт', 'regional' => 'ce_RU'],
        //'cgg'         => ['name' => 'Chiga',                'script' => 'Latn', 'native' => 'Rukiga', 'regional' => ''],
        //'ch'          => ['name' => 'Chamorro',             'script' => 'Latn', 'native' => 'Chamoru', 'regional' => ''],
        //'chr'         => ['name' => 'Cherokee',             'script' => 'Cher', 'native' => 'ᏣᎳᎩ', 'regional' => ''],
        //'co'          => ['name' => 'Corsican',             'script' => 'Latn', 'native' => 'corsu', 'regional' => ''],
        //'cr'          => ['name' => 'Cree',                 'script' => 'Cans', 'native' => 'ᓀᐦᐃᔭᐍᐏᐣ', 'regional' => ''],
        //'cs'          => ['name' => 'Czech',                'script' => 'Latn', 'native' => 'čeština', 'regional' => 'cs_CZ'],
        //'cu'          => ['name' => 'Church Slavic',        'script' => 'Cyrl', 'native' => 'ѩзыкъ словѣньскъ', 'regional' => ''],
        //'cv'          => ['name' => 'Chuvash',              'script' => 'Cyrl', 'native' => 'чӑваш чӗлхи', 'regional' => 'cv_RU'],
        //'cy'          => ['name' => 'Welsh',                'script' => 'Latn', 'native' => 'Cymraeg', 'regional' => 'cy_GB'],
        //'da'          => ['name' => 'Danish',               'script' => 'Latn', 'native' => 'dansk', 'regional' => 'da_DK'],
        //'dav'         => ['name' => 'Dawida',               'script' => 'Latn', 'native' => 'Kitaita', 'regional' => ''],
        //'de'          => ['name' => 'German',               'script' => 'Latn', 'native' => 'Deutsch', 'regional' => 'de_DE'],
        //'de-AT'       => ['name' => 'Austrian German',      'script' => 'Latn', 'native' => 'Österreichisches Deutsch', 'regional' => 'de_AT'],
        //'de-CH'       => ['name' => 'Swiss High German',    'script' => 'Latn', 'native' => 'Schweizer Hochdeutsch', 'regional' => 'de_CH'],
        //'dje'         => ['name' => 'Zarma',                'script' => 'Latn', 'native' => 'Zarmaciine', 'regional' => ''],
        //'doi'         => ['name' => 'Dogri',                'script' => 'Deva', 'native' => 'डोगरी', 'regional' => 'doi_IN'],
        //'dua'         => ['name' => 'Duala',                'script' => 'Latn', 'native' => 'duálá', 'regional' => ''],
        //'dv'          => ['name' => 'Divehi',               'script' => 'Thaa', 'native' => 'ދިވެހިބަސް', 'regional' => 'dv_MV'],
        //'dyo'         => ['name' => 'Jola-Fonyi',           'script' => 'Latn', 'native' => 'joola', 'regional' => ''],
        //'dz'          => ['name' => 'Dzongkha',             'script' => 'Tibt', 'native' => 'རྫོང་ཁ', 'regional' => 'dz_BT'],
        //'ebu'         => ['name' => 'Kiembu',               'script' => 'Latn', 'native' => 'Kĩembu', 'regional' => ''],
        //'ee'          => ['name' => 'Ewe',                  'script' => 'Latn', 'native' => 'eʋegbe', 'regional' => ''],
        //'el'          => ['name' => 'Greek',                'script' => 'Grek', 'native' => 'Ελληνικά', 'regional' => 'el_GR'],
        'en'          => ['name' => 'English',              'script' => 'Latn', 'native' => 'English', 'regional' => 'en_GB'],
        //'en-AU'       => ['name' => 'Australian English',   'script' => 'Latn', 'native' => 'Australian English', 'regional' => 'en_AU'],
        //'en-GB'       => ['name' => 'British English',      'script' => 'Latn', 'native' => 'British English', 'regional' => 'en_GB'],
        //'en-US'       => ['name' => 'U.S. English',         'script' => 'Latn', 'native' => 'U.S. English', 'regional' => 'en_US'],
        //'eo'          => ['name' => 'Esperanto',            'script' => 'Latn', 'native' => 'esperanto', 'regional' => ''],
        'es'          => ['name' => 'Spanish',              'script' => 'Latn', 'native' => 'español', 'regional' => 'es_ES'],
        //'et'          => ['name' => 'Estonian',             'script' => 'Latn', 'native' => 'eesti', 'regional' => 'et_EE'],
        //'eu'          => ['name' => 'Basque',               'script' => 'Latn', 'native' => 'euskara', 'regional' => 'eu_ES'],
        //'ewo'         => ['name' => 'Ewondo',               'script' => 'Latn', 'native' => 'ewondo', 'regional' => ''],
        //'fa'          => ['name' => 'Persian',              'script' => 'Arab', 'native' => 'فارسی', 'regional' => 'fa_IR'],
        //'ff'          => ['name' => 'Fulah',                'script' => 'Latn', 'native' => 'Pulaar', 'regional' => 'ff_SN'],
        //'fi'          => ['name' => 'Finnish',              'script' => 'Latn', 'native' => 'suomi', 'regional' => 'fi_FI'],
        //'fil'         => ['name' => 'Filipino',             'script' => 'Latn', 'native' => 'Filipino', 'regional' => 'fil_PH'],
        //'fj'          => ['name' => 'Fijian',               'script' => 'Latn', 'native' => 'vosa Vakaviti', 'regional' => ''],
        //'fo'          => ['name' => 'Faroese',              'script' => 'Latn', 'native' => 'føroyskt', 'regional' => 'fo_FO'],
        //'fr'          => ['name' => 'French',               'script' => 'Latn', 'native' => 'français', 'regional' => 'fr_FR'],
        //'fr-CA'       => ['name' => 'Canadian French',      'script' => 'Latn', 'native' => 'français canadien', 'regional' => 'fr_CA'],
        //'fur'         => ['name' => 'Friulian',             'script' => 'Latn', 'native' => 'furlan', 'regional' => 'fur_IT'],
        //'fy'          => ['name' => 'Western Frisian',      'script' => 'Latn', 'native' => 'frysk', 'regional' => 'fy_DE'],
        //'ga'          => ['name' => 'Irish',                'script' => 'Latn', 'native' => 'Gaeilge', 'regional' => 'ga_IE'],
        //'gaa'         => ['name' => 'Ga',                   'script' => 'Latn', 'native' => 'Ga', 'regional' => ''],
        //'gd'          => ['name' => 'Scottish Gaelic',      'script' => 'Latn', 'native' => 'Gàidhlig', 'regional' => 'gd_GB'],
        //'gl'          => ['name' => 'Galician',             'script' => 'Latn', 'native' => 'galego', 'regional' => 'gl_ES'],
        //'gn'          => ['name' => 'Guaraní',              'script' => 'Latn', 'native' => 'Avañe’ẽ', 'regional' => ''],
        //'gsw'         => ['name' => 'Swiss German',         'script' => 'Latn', 'native' => 'Schwiizertüütsch', 'regional' => ''],
        //'gu'          => ['name' => 'Gujarati',             'script' => 'Gujr', 'native' => 'ગુજરાતી', 'regional' => 'gu_IN'],
        //'guz'         => ['name' => 'Ekegusii',             'script' => 'Latn', 'native' => 'Ekegusii', 'regional' => ''],
        //'gv'          => ['name' => 'Manx',                 'script' => 'Latn', 'native' => 'Gaelg', 'regional' => 'gv_GB'],
        //'ha'          => ['name' => 'Hausa',                'script' => 'Latn', 'native' => 'Hausa', 'regional' => 'ha_NG'],
        //'haw'         => ['name' => 'Hawaiian',             'script' => 'Latn', 'native' => 'ʻŌlelo Hawaiʻi', 'regional' => ''],
        //'he'          => ['name' => 'Hebrew',               'script' => 'Hebr', 'native' => 'עברית', 'regional' => 'he_IL'],
        //'hi'          => ['name' => 'Hindi',                'script' => 'Deva', 'native' => 'हिन्दी', 'regional' => 'hi_IN'],
        //'ho'          => ['name' => 'Hiri Motu',            'script' => 'Latn', 'native' => 'Hiri Motu', 'regional' => ''],
        //'hr'          => ['name' => 'Croatian',             'script' => 'Latn', 'native' => 'hrvatski', 'regional' => 'hr_HR'],
        //'ht'          => ['name' => 'Haitian',              'script' => 'Latn', 'native' => 'Kreyòl ayisyen', 'regional' => 'ht_HT'],
        //'hu'          => ['name' => 'Hungarian',            'script' => 'Latn', 'native' => 'magyar', 'regional' => 'hu_HU'],
        //'hy'          => ['name' => 'Armenian',             'script' => 'Armn', 'native' => 'Հայերեն', 'regional' => 'hy_AM'],
        //'hz'          => ['name' => 'Herero',               'script' => 'Latn', 'native' => 'Otjiherero', 'regional' => ''],
        //'ia'          => ['name' => 'Interlingua',          'script' => 'Latn', 'native' => 'interlingua', 'regional' => 'ia_FR'],
        //'id'          => ['name' => 'Indonesian',           'script' => 'Latn', 'native' => 'Bahasa Indonesia', 'regional' => 'id_ID'],
        //'ig'          => ['name' => 'Igbo',                 'script' => 'Latn', 'native' => 'Igbo', 'regional' => 'ig_NG'],
        //'ii'          => ['name' => 'Sichuan Yi',           'script' => 'Yiii', 'native' => 'ꆈꌠꉙ', 'regional' => ''],
        //'ik'          => ['name' => 'Inupiaq',              'script' => 'Latn', 'native' => 'Iñupiaq', 'regional' => 'ik_CA'],
        //'io'          => ['name' => 'Ido',                  'script' => 'Latn', 'native' => 'Ido', 'regional' => ''],
        //'is'          => ['name' => 'Icelandic',            'script' => 'Latn', 'native' => 'íslenska', 'regional' => 'is_IS'],
        //'it'          => ['name' => 'Italian',              'script' => 'Latn', 'native' => 'italiano', 'regional' => 'it_IT'],
        //'iu'          => ['name' => 'Inuktitut (Canadian Aboriginal Syllabics)', 'script' => 'Cans', 'native' => 'ᐃᓄᒃᑎᑐᑦ', 'regional' => 'iu_CA'],
        //'iu-Latn'     => ['name' => 'Inuktitut (Latin)',    'script' => 'Latn', 'native' => 'Inuktitut', 'regional' => 'iu_CA'],
        //'ja'          => ['name' => 'Japanese',             'script' => 'Jpan', 'native' => '日本語', 'regional' => 'ja_JP'],
        //'jmc'         => ['name' => 'Machame',              'script' => 'Latn', 'native' => 'Kimachame', 'regional' => ''],
        //'jv'          => ['name' => 'Javanese (Latin)',     'script' => 'Latn', 'native' => 'Basa Jawa', 'regional' => ''],
        //'jv-Java'     => ['name' => 'Javanese (Javanese)',  'script' => 'Java', 'native' => 'ꦧꦱꦗꦮ', 'regional' => ''],
        //'ka'          => ['name' => 'Georgian',             'script' => 'Geor', 'native' => 'ქართული', 'regional' => 'ka_GE'],
        //'kab'         => ['name' => 'Kabyle',               'script' => 'Latn', 'native' => 'Taqbaylit', 'regional' => 'kab_DZ'],
        //'kaj'         => ['name' => 'Jju',                  'script' => 'Latn', 'native' => 'Kaje', 'regional' => ''],
        //'kam'         => ['name' => 'Kamba',                'script' => 'Latn', 'native' => 'Kikamba', 'regional' => ''],
        //'kcg'         => ['name' => 'Tyap',                 'script' => 'Latn', 'native' => 'Katab', 'regional' => ''],
        //'kde'         => ['name' => 'Makonde',              'script' => 'Latn', 'native' => 'Chimakonde', 'regional' => ''],
        //'kea'         => ['name' => 'Kabuverdianu',         'script' => 'Latn', 'native' => 'kabuverdianu', 'regional' => ''],
        //'kg'          => ['name' => 'Kongo',                'script' => 'Latn', 'native' => 'Kikongo', 'regional' => ''],
        //'khq'         => ['name' => 'Koyra Chiini',         'script' => 'Latn', 'native' => 'Koyra ciini', 'regional' => ''],
        //'ki'          => ['name' => 'Kikuyu',               'script' => 'Latn', 'native' => 'Gikuyu', 'regional' => ''],
        //'kj'          => ['name' => 'Kuanyama',             'script' => 'Latn', 'native' => 'Kwanyama', 'regional' => ''],
        //'kk'          => ['name' => 'Kazakh',               'script' => 'Cyrl', 'native' => 'қазақ тілі', 'regional' => 'kk_KZ'],
        //'kl'          => ['name' => 'Kalaallisut',          'script' => 'Latn', 'native' => 'kalaallisut', 'regional' => 'kl_GL'],
        //'kln'         => ['name' => 'Kalenjin',             'script' => 'Latn', 'native' => 'Kalenjin', 'regional' => ''],
        //'km'          => ['name' => 'Khmer',                'script' => 'Khmr', 'native' => 'ភាសាខ្មែរ', 'regional' => 'km_KH'],
        //'kn'          => ['name' => 'Kannada',              'script' => 'Knda', 'native' => 'ಕನ್ನಡ', 'regional' => 'kn_IN'],
        //'ko'          => ['name' => 'Korean',               'script' => 'Hang', 'native' => '한국어', 'regional' => 'ko_KR'],
        //'kok'         => ['name' => 'Konkani',              'script' => 'Deva', 'native' => 'कोंकणी', 'regional' => 'kok_IN'],
        //'kr'          => ['name' => 'Kanuri',               'script' => 'Latn', 'native' => 'Kanuri', 'regional' => ''],
        //'ks'          => ['name' => 'Kashmiri (Arabic)',    'script' => 'Arab', 'native' => 'کأشُر', 'regional' => 'ks_IN'],
        //'ks-Deva'     => ['name' => 'Kashmiri (Devaganari)', 'script' => 'Deva', 'native' => 'कॉशुर', 'regional' => 'ks_IN'],
        //'ksb'         => ['name' => 'Shambala',             'script' => 'Latn', 'native' => 'Kishambaa', 'regional' => ''],
        //'ksf'         => ['name' => 'Bafia',                'script' => 'Latn', 'native' => 'rikpa', 'regional' => ''],
        //'ksh'         => ['name' => 'Kölsch',               'script' => 'Latn', 'native' => 'Kölsch', 'regional' => ''],
        //'ku'          => ['name' => 'Kurdish',              'script' => 'Arab', 'native' => 'کوردی', 'regional' => 'ku_TR'],
        //'kv'          => ['name' => 'Komi',                 'script' => 'Cyrl', 'native' => 'коми кыв', 'regional' => ''],
        //'kw'          => ['name' => 'Cornish',              'script' => 'Latn', 'native' => 'kernewek', 'regional' => 'kw_GB'],
        //'ky'          => ['name' => 'Kyrgyz',               'script' => 'Cyrl', 'native' => 'Кыргыз', 'regional' => 'ky_KG'],
        //'la'          => ['name' => 'Latin',                'script' => 'Latn', 'native' => 'latine', 'regional' => ''],
        //'lag'         => ['name' => 'Langi',                'script' => 'Latn', 'native' => 'Kɨlaangi', 'regional' => ''],
        //'lah'         => ['name' => 'Lahnda',               'script' => 'Latn', 'native' => 'Lahnda', 'regional' => ''],
        //'lb'          => ['name' => 'Luxembourgish',        'script' => 'Latn', 'native' => 'Lëtzebuergesch', 'regional' => 'lb_LU'],
        //'lg'          => ['name' => 'Ganda',                'script' => 'Latn', 'native' => 'Luganda', 'regional' => 'lg_UG'],
        //'li'          => ['name' => 'Limburgish',           'script' => 'Latn', 'native' => 'Limburgs', 'regional' => 'li_BE'],
        //'ln'          => ['name' => 'Lingala',              'script' => 'Latn', 'native' => 'lingála', 'regional' => ''],
        //'lo'          => ['name' => 'Lao',                  'script' => 'Laoo', 'native' => 'ລາວ', 'regional' => 'lo_LA'],
        //'lt'          => ['name' => 'Lithuanian',           'script' => 'Latn', 'native' => 'lietuvių', 'regional' => 'lt_LT'],
        //'lu'          => ['name' => 'Luba-Katanga',         'script' => 'Latn', 'native' => 'Tshiluba', 'regional' => 've_ZA'],
        //'luo'         => ['name' => 'Luo',                  'script' => 'Latn', 'native' => 'Dholuo', 'regional' => ''],
        //'luy'         => ['name' => 'Oluluyia',             'script' => 'Latn', 'native' => 'Luluhia', 'regional' => ''],
        //'lv'          => ['name' => 'Latvian',              'script' => 'Latn', 'native' => 'latviešu', 'regional' => 'lv_LV'],
        //'mai'         => ['name' => 'Maithili',             'script' => 'Tirh', 'native' => 'मैथिली', 'regional' => 'mai_IN'],
        //'mas'         => ['name' => 'Masai',                'script' => 'Latn', 'native' => 'ɔl-Maa', 'regional' => ''],
        //'mer'         => ['name' => 'Kimîîru',              'script' => 'Latn', 'native' => 'Kĩmĩrũ', 'regional' => ''],
        //'mfe'         => ['name' => 'Morisyen',             'script' => 'Latn', 'native' => 'kreol morisien', 'regional' => ''],
        //'mg'          => ['name' => 'Malagasy',             'script' => 'Latn', 'native' => 'Malagasy', 'regional' => 'mg_MG'],
        //'mgh'         => ['name' => 'Makhuwa-Meetto',       'script' => 'Latn', 'native' => 'Makua', 'regional' => ''],
        //'mh'          => ['name' => 'Marshallese',          'script' => 'Latn', 'native' => 'Kajin M̧ajeļ', 'regional' => 'mh_MH'],
        //'mi'          => ['name' => 'Māori',                'script' => 'Latn', 'native' => 'Māori', 'regional' => 'mi_NZ'],
        //'mk'          => ['name' => 'Macedonian',           'script' => 'Cyrl', 'native' => 'македонски', 'regional' => 'mk_MK'],
        //'ml'          => ['name' => 'Malayalam',            'script' => 'Mlym', 'native' => 'മലയാളം', 'regional' => 'ml_IN'],
        //'mn'          => ['name' => 'Mongolian (Cyrillic)', 'script' => 'Cyrl', 'native' => 'монгол', 'regional' => 'mn_MN'],
        //'mn-Mong'     => ['name' => 'Mongolian (Mongolian)', 'script' => 'Mong', 'native' => 'ᠮᠣᠨᠭᠭᠣᠯ ᠬᠡᠯᠡ', 'regional' => 'mn_MN'],
        //'mni'         => ['name' => 'Manipuri',             'script' => 'Beng', 'native' => 'মৈতৈ', 'regional' => 'mni_IN'],
        //'mr'          => ['name' => 'Marathi',              'script' => 'Deva', 'native' => 'मराठी', 'regional' => 'mr_IN'],
        //'ms'          => ['name' => 'Malay',                'script' => 'Latn', 'native' => 'Bahasa Melayu', 'regional' => 'ms_MY'],
        //'mt'          => ['name' => 'Maltese',              'script' => 'Latn', 'native' => 'Malti', 'regional' => 'mt_MT'],
        //'mtr'         => ['name' => 'Mewari',               'script' => 'Latn', 'native' => 'Mewari', 'regional' => ''],
        //'mua'         => ['name' => 'Mundang',              'script' => 'Latn', 'native' => 'Mundang', 'regional' => ''],
        //'my'          => ['name' => 'Burmese',              'script' => 'Mymr', 'native' => 'မြန်မာဘာသာ', 'regional' => 'my_MM'],
        //'na'          => ['name' => 'Nauru',                'script' => 'Latn', 'native' => 'Ekakairũ Naoero', 'regional' => ''],
        //'naq'         => ['name' => 'Nama',                 'script' => 'Latn', 'native' => 'Khoekhoegowab', 'regional' => ''],
        //'nb'          => ['name' => 'Norwegian Bokmål',     'script' => 'Latn', 'native' => 'Bokmål', 'regional' => 'nb_NO'],
        //'nd'          => ['name' => 'North Ndebele',        'script' => 'Latn', 'native' => 'isiNdebele', 'regional' => ''],
        //'nds'         => ['name' => 'Low German',           'script' => 'Latn', 'native' => 'Plattdüütsch', 'regional' => 'nds_DE'],
        //'ne'          => ['name' => 'Nepali',               'script' => 'Deva', 'native' => 'नेपाली', 'regional' => ''],
        //'ng'          => ['name' => 'Ndonga',               'script' => 'Latn', 'native' => 'OshiNdonga', 'regional' => ''],
        //'nl'          => ['name' => 'Dutch',                'script' => 'Latn', 'native' => 'Nederlands', 'regional' => 'nl_NL'],
        //'nmg'         => ['name' => 'Kwasio',               'script' => 'Latn', 'native' => 'ngumba', 'regional' => ''],
        //'nn'          => ['name' => 'Norwegian Nynorsk',    'script' => 'Latn', 'native' => 'nynorsk', 'regional' => 'nn_NO'],
        //'nr'          => ['name' => 'South Ndebele',        'script' => 'Latn', 'native' => 'isiNdebele', 'regional' => 'nr_ZA'],
        //'nso'         => ['name' => 'Northern Sotho',       'script' => 'Latn', 'native' => 'Sesotho sa Leboa', 'regional' => 'nso_ZA'],
        //'nus'         => ['name' => 'Nuer',                 'script' => 'Latn', 'native' => 'Thok Nath', 'regional' => ''],
        //'nv'          => ['name' => 'Navajo',               'script' => 'Latn', 'native' => 'Diné bizaad', 'regional' => ''],
        //'ny'          => ['name' => 'Chewa',                'script' => 'Latn', 'native' => 'chiCheŵa', 'regional' => ''],
        //'nyn'         => ['name' => 'Nyankole',             'script' => 'Latn', 'native' => 'Runyankore', 'regional' => ''],
        //'oc'          => ['name' => 'Occitan',              'script' => 'Latn', 'native' => 'occitan', 'regional' => 'oc_FR'],
        //'oj'          => ['name' => 'Ojibwa',               'script' => 'Cans', 'native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'regional' => ''],
        //'om'          => ['name' => 'Oromo',                'script' => 'Latn', 'native' => 'Oromoo', 'regional' => 'om_ET'],
        //'or'          => ['name' => 'Oriya',                'script' => 'Orya', 'native' => 'ଓଡ଼ିଆ', 'regional' => 'or_IN'],
        //'os'          => ['name' => 'Ossetic',              'script' => 'Cyrl', 'native' => 'Ирон', 'regional' => 'os_RU'],
        //'pa'          => ['name' => 'Punjabi (Gurmukhi)',   'script' => 'Guru', 'native' => 'ਪੰਜਾਬੀ', 'regional' => 'pa_IN'],
        //'pa-Arab'     => ['name' => 'Punjabi (Arabic)',     'script' => 'Arab', 'native' => 'پنجاب', 'regional' => 'pa_IN'],
        //'pi'          => ['name' => 'Pahari-Potwari',       'script' => 'Latn', 'native' => 'Pāli', 'regional' => ''],
        //'pl'          => ['name' => 'Polish',               'script' => 'Latn', 'native' => 'polski', 'regional' => 'pl_PL'],
        //'pra'         => ['name' => 'Prakrit',              'script' => 'Deva', 'native' => 'प्राकृत', 'regional' => ''],
        //'ps'          => ['name' => 'Pashto',               'script' => 'Arab', 'native' => 'پښتو', 'regional' => 'ps_AF'],
        //'pt'          => ['name' => 'Portuguese',           'script' => 'Latn', 'native' => 'português', 'regional' => 'pt_PT'],
        //'pt-BR'       => ['name' => 'Brazilian Portuguese', 'script' => 'Latn', 'native' => 'português do Brasil', 'regional' => 'pt_BR'],
        //'qu'          => ['name' => 'Quechua',              'script' => 'Latn', 'native' => 'Runa Simi', 'regional' => ''],
        //'raj'         => ['name' => 'Rajasthani',           'script' => 'Deva', 'native' => 'राजस्थानी', 'regional' => ''],
        //'rm'          => ['name' => 'Romansh',              'script' => 'Latn', 'native' => 'rumantsch', 'regional' => ''],
        //'rn'          => ['name' => 'Rundi',                'script' => 'Latn', 'native' => 'Ikirundi', 'regional' => ''],
        //'ro'          => ['name' => 'Romanian',             'script' => 'Latn', 'native' => 'română', 'regional' => 'ro_RO'],
        //'rof'         => ['name' => 'Rombo',                'script' => 'Latn', 'native' => 'Kihorombo', 'regional' => ''],
        //'ru'          => ['name' => 'Russian',              'script' => 'Cyrl', 'native' => 'русский', 'regional' => 'ru_RU'],
        //'rw'          => ['name' => 'Kinyarwanda',          'script' => 'Latn', 'native' => 'Kinyarwanda', 'regional' => 'rw_RW'],
        //'rwk'         => ['name' => 'Rwa',                  'script' => 'Latn', 'native' => 'Kiruwa', 'regional' => ''],
        //'sa'          => ['name' => 'Sanskrit',             'script' => 'Deva', 'native' => 'संस्कृतम्', 'regional' => 'sa_IN'],
        //'sah'         => ['name' => 'Yakut',                'script' => 'Cyrl', 'native' => 'саха тыла', 'regional' => ''],
        //'saq'         => ['name' => 'Samburu',              'script' => 'Latn', 'native' => 'Kisampur', 'regional' => ''],
        //'sbp'         => ['name' => 'Sileibi',              'script' => 'Latn', 'native' => 'Ishisangu', 'regional' => ''],
        //'sc'          => ['name' => 'Sardinian',            'script' => 'Latn', 'native' => 'sardu', 'regional' => 'sc_IT'],
        //'sd'          => ['name' => 'Sindhi',               'script' => 'Arab', 'native' => 'سنڌي', 'regional' => 'sd_IN'],
        //'se'          => ['name' => 'Northern Sami',        'script' => 'Latn', 'native' => 'davvisámegiella', 'regional' => 'se_NO'],
        //'seh'         => ['name' => 'Sena',                 'script' => 'Latn', 'native' => 'sena', 'regional' => ''],
        //'ses'         => ['name' => 'Songhay',              'script' => 'Latn', 'native' => 'Koyraboro senni', 'regional' => ''],
        //'sg'          => ['name' => 'Sango',                'script' => 'Latn', 'native' => 'Sängö', 'regional' => ''],
        //'sh'          => ['name' => 'Serbo-Croatian',       'script' => 'Latn', 'native' => 'srpskohrvatski', 'regional' => ''],
        //'shi'         => ['name' => 'Tachelhit (Latin)',    'script' => 'Latn', 'native' => 'Tashelhit', 'regional' => ''],
        //'shi-Tfng'    => ['name' => 'Tachelhit (Tifinagh)', 'script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'regional' => ''],
        //'si'          => ['name' => 'Sinhala',              'script' => 'Sinh', 'native' => 'සිංහල', 'regional' => 'si_LK'],
        //'sid'         => ['name' => 'Sidamo',               'script' => 'Latn', 'native' => 'Sidaamu Afo', 'regional' => 'sid_ET'],
        //'sk'          => ['name' => 'Slovak',               'script' => 'Latn', 'native' => 'slovenčina', 'regional' => 'sk_SK'],
        //'sl'          => ['name' => 'Slovene',              'script' => 'Latn', 'native' => 'slovenščina', 'regional' => 'sl_SI'],
        //'sm'          => ['name' => 'Samoan',               'script' => 'Latn', 'native' => 'Gagana fa’a Sāmoa', 'regional' => ''],
        //'sn'          => ['name' => 'Shona',                'script' => 'Latn', 'native' => 'chiShona', 'regional' => ''],
        //'so'          => ['name' => 'Somali',               'script' => 'Latn', 'native' => 'Soomaali', 'regional' => 'so_SO'],
        //'sq'          => ['name' => 'Albanian',             'script' => 'Latn', 'native' => 'shqip', 'regional' => 'sq_AL'],
        //'sr'          => ['name' => 'Serbian (Cyrillic)',   'script' => 'Cyrl', 'native' => 'Српски', 'regional' => 'sr_RS'],
        //'sr-Latn'     => ['name' => 'Serbian (Latin)',      'script' => 'Latn', 'native' => 'Srpski', 'regional' => 'sr_RS'],
        //'ss'          => ['name' => 'Swati',                'script' => 'Latn', 'native' => 'Siswati', 'regional' => 'ss_ZA'],
        //'ssy'         => ['name' => 'Saho',                 'script' => 'Latn', 'native' => 'Saho', 'regional' => ''],
        //'st'          => ['name' => 'Southern Sotho',       'script' => 'Latn', 'native' => 'Sesotho', 'regional' => 'st_ZA'],
        //'su'          => ['name' => 'Sundanese',            'script' => 'Latn', 'native' => 'Basa Sunda', 'regional' => ''],
        //'sv'          => ['name' => 'Swedish',              'script' => 'Latn', 'native' => 'svenska', 'regional' => 'sv_SE'],
        //'sw'          => ['name' => 'Swahili',              'script' => 'Latn', 'native' => 'Kiswahili', 'regional' => 'sw_KE'],
        //'swc'         => ['name' => 'Congo Swahili',        'script' => 'Latn', 'native' => 'Kiswahili ya Kongo', 'regional' => ''],
        //'ta'          => ['name' => 'Tamil',                'script' => 'Taml', 'native' => 'தமிழ்', 'regional' => 'ta_IN'],
        //'te'          => ['name' => 'Telugu',               'script' => 'Telu', 'native' => 'తెలుగు', 'regional' => 'te_IN'],
        //'teo'         => ['name' => 'Teso',                 'script' => 'Latn', 'native' => 'Kiteso', 'regional' => ''],
        //'tg'          => ['name' => 'Tajik (Cyrillic)',     'script' => 'Cyrl', 'native' => 'тоҷикӣ', 'regional' => 'tg_TJ'],
        //'tg-Arab'     => ['name' => 'Tajik (Arabic)',       'script' => 'Arab', 'native' => 'تاجیکی', 'regional' => 'tg_TJ'],
        //'tg-Latn'     => ['name' => 'Tajik (Latin)',        'script' => 'Latn', 'native' => 'tojikī', 'regional' => 'tg_TJ'],
        //'th'          => ['name' => 'Thai',                 'script' => 'Thai', 'native' => 'ไทย', 'regional' => 'th_TH'],
        //'ti'          => ['name' => 'Tigrinya',             'script' => 'Ethi', 'native' => 'ትግርኛ', 'regional' => 'ti_ET'],
        //'tig'         => ['name' => 'Tigre',                'script' => 'Ethi', 'native' => 'ትግረ', 'regional' => 'tig_ER'],
        //'tk'          => ['name' => 'Turkmen',              'script' => 'Cyrl', 'native' => 'түркменче', 'regional' => 'tk_TM'],
        //'tl'          => ['name' => 'Tagalog',              'script' => 'Latn', 'native' => 'Tagalog', 'regional' => 'tl_PH'],
        //'tn'          => ['name' => 'Tswana',               'script' => 'Latn', 'native' => 'Setswana', 'regional' => 'tn_ZA'],
        //'to'          => ['name' => 'Tongan',               'script' => 'Latn', 'native' => 'lea fakatonga', 'regional' => ''],
        //'tr'          => ['name' => 'Turkish',              'script' => 'Latn', 'native' => 'Türkçe', 'regional' => 'tr_TR'],
        //'trv'         => ['name' => 'Taroko',               'script' => 'Latn', 'native' => 'Seediq', 'regional' => ''],
        //'ts'          => ['name' => 'Tsonga',               'script' => 'Latn', 'native' => 'Xitsonga', 'regional' => 'ts_ZA'],
        //'tt'          => ['name' => 'Tatar',                'script' => 'Cyrl', 'native' => 'татар теле', 'regional' => 'tt_RU'],
        //'tw'          => ['name' => 'Twi',                  'script' => 'Latn', 'native' => 'Twi', 'regional' => ''],
        //'twq'         => ['name' => 'Tasawaq',              'script' => 'Latn', 'native' => 'Tasawaq senni', 'regional' => ''],
        //'ty'          => ['name' => 'Tahitian',             'script' => 'Latn', 'native' => 'Reo Māohi', 'regional' => ''],
        //'tzm'         => ['name' => 'Central Atlas Tamazight (Tifinagh)', 'script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'regional' => ''],
        //'tzm-Latn'    => ['name' => 'Central Atlas Tamazight (Latin)', 'script' => 'Latn', 'native' => 'Tamazight', 'regional' => ''],
        //'ug'          => ['name' => 'Uyghur',               'script' => 'Arab', 'native' => 'ئۇيغۇرچە', 'regional' => 'ug_CN'],
        //'uk'          => ['name' => 'Ukrainian',            'script' => 'Cyrl', 'native' => 'українська', 'regional' => 'uk_UA'],
        //'ur'          => ['name' => 'Urdu',                 'script' => 'Arab', 'native' => 'اردو', 'regional' => 'ur_PK'],
        //'uz'          => ['name' => 'Uzbek (Cyrillic)',     'script' => 'Cyrl', 'native' => 'Ўзбек', 'regional' => 'uz_UZ'],
        //'uz-Arab'     => ['name' => 'Uzbek (Arabic)',       'script' => 'Arab', 'native' => 'اۉزبېک', 'regional' => ''],
        //'uz-Latn'     => ['name' => 'Uzbek (Latin)',        'script' => 'Latn', 'native' => 'oʼzbekcha', 'regional' => 'uz_UZ'],
        //'vai'         => ['name' => 'Vai (Vai)',            'script' => 'Vaii', 'native' => 'ꕙꔤ', 'regional' => ''],
        //'vai-Latn'    => ['name' => 'Vai (Latin)',          'script' => 'Latn', 'native' => 'Viyamíĩ', 'regional' => ''],
        //'ve'          => ['name' => 'Venda',                'script' => 'Latn', 'native' => 'Tshivenḓa', 'regional' => ''],
        //'vi'          => ['name' => 'Vietnamese',           'script' => 'Latn', 'native' => 'Tiếng Việt', 'regional' => 'vi_VN'],
        //'vo'          => ['name' => 'Volapük',              'script' => 'Latn', 'native' => 'Volapük', 'regional' => ''],
        //'wa'          => ['name' => 'Walloon',              'script' => 'Latn', 'native' => 'Walon', 'regional' => 'wa_BE'],
        //'wae'         => ['name' => 'Walser',               'script' => 'Latn', 'native' => 'Walser', 'regional' => 'wae_CH'],
        //'wal'         => ['name' => 'Wolaytta',             'script' => 'Ethi', 'native' => 'ወላይታቱ', 'regional' => 'wal_ET'],
        //'wen'         => ['name' => 'Sorbian',              'script' => 'Latn', 'native' => 'Wendic', 'regional' => ''],
        //'wo'          => ['name' => 'Wolof',                'script' => 'Latn', 'native' => 'Wolof', 'regional' => 'wo_SN'],
        //'xh'          => ['name' => 'Xhosa',                'script' => 'Latn', 'native' => 'isiXhosa', 'regional' => 'xh_ZA'],
        //'xog'         => ['name' => 'Soga',                 'script' => 'Latn', 'native' => 'Olusoga', 'regional' => ''],
        //'yav'         => ['name' => 'Yangben',              'script' => 'Latn', 'native' => 'nuasue', 'regional' => ''],
        //'yi'          => ['name' => 'Yiddish',              'script' => 'Hebr', 'native' => 'ייִדיש', 'regional' => 'yi_US'],
        //'yo'          => ['name' => 'Yoruba',               'script' => 'Latn', 'native' => 'Èdè Yorùbá', 'regional' => 'yo_NG'],
        //'yue'         => ['name' => 'Yue',                  'script' => 'Hant', 'native' => '廣州話', 'regional' => 'yue_HK'],
        //'zh'          => ['name' => 'Chinese (Simplified)', 'script' => 'Hans', 'native' => '简体中文', 'regional' => 'zh_CN'],
        //'zh-Hant'     => ['name' => 'Chinese (Traditional)', 'script' => 'Hant', 'native' => '繁體中文', 'regional' => 'zh_CN'],
        //'zu'          => ['name' => 'Zulu',                 'script' => 'Latn', 'native' => 'isiZulu', 'regional' => 'zu_ZA'],
    ],

    // Negotiate for the user locale using the Accept-Language header if it's not defined in the URL?
    // If false, system will take app.php locale attribute
    'useAcceptLanguageHeader' => true,

    // If LaravelLocalizationRedirectFilter is active and hideDefaultLocaleInURL
    // is true, the url would not have the default application language
    //
    // IMPORTANT - When hideDefaultLocaleInURL is set to true, the unlocalized root is treated as the applications default locale "app.locale".
    // Because of this language negotiation using the Accept-Language header will NEVER occur when hideDefaultLocaleInURL is true.
    //
    'hideDefaultLocaleInURL' => false,

    // If you want to display the locales in particular order in the language selector you should write the order here.
    //CAUTION: Please consider using the appropriate locale code otherwise it will not work
    //Example: 'localesOrder' => ['es','en'],
    'localesOrder' => [],
];
