<?php

return [

    // Uncomment the languages that your site supports - or add new ones.
    // These are sorted by the native name, which is the order you might show them in a language selector.
    // Regional languages are sorted by their base language, so "British English" sorts as "English, British"
    'supportedLocales' => [
        'ace'         => ['name' => 'Achinese',               'script' => 'Latn', 'native' => 'Aceh', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_ACE', null)],
        'af'          => ['name' => 'Afrikaans',              'script' => 'Latn', 'native' => 'Afrikaans', 'regional' => 'af_ZA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_AF_AF', null)],
        'agq'         => ['name' => 'Aghem',                  'script' => 'Latn', 'native' => 'Aghem', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_AGQ', null)],
        'ak'          => ['name' => 'Akan',                   'script' => 'Latn', 'native' => 'Akan', 'regional' => 'ak_GH', 'domain' => env('LOCALIZATION_DOMAIN_NAME_AK', null)],
        'an'          => ['name' => 'Aragonese',              'script' => 'Latn', 'native' => 'aragonés', 'regional' => 'an_ES', 'domain' => env('LOCALIZATION_DOMAIN_NAME_AN', null)],
        'cch'         => ['name' => 'Atsam',                  'script' => 'Latn', 'native' => 'Atsam', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_CCH', null)],
        'gn'          => ['name' => 'Guaraní',                'script' => 'Latn', 'native' => 'Avañe’ẽ', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_GN', null)],
        'ae'          => ['name' => 'Avestan',                'script' => 'Latn', 'native' => 'avesta', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_AE', null)],
        'ay'          => ['name' => 'Aymara',                 'script' => 'Latn', 'native' => 'aymar aru', 'regional' => 'ay_PE', 'domain' => env('LOCALIZATION_DOMAIN_NAME_AY', null)],
        'az'          => ['name' => 'Azerbaijani (Latin)',    'script' => 'Latn', 'native' => 'azərbaycanca', 'regional' => 'az_AZ', 'domain' => env('LOCALIZATION_DOMAIN_NAME_AZ', null)],
        'id'          => ['name' => 'Indonesian',             'script' => 'Latn', 'native' => 'Bahasa Indonesia', 'regional' => 'id_ID', 'domain' => env('LOCALIZATION_DOMAIN_NAME_ID', null)],
        'ms'          => ['name' => 'Malay',                  'script' => 'Latn', 'native' => 'Bahasa Melayu', 'regional' => 'ms_MY', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MS', null)],
        'bm'          => ['name' => 'Bambara',                'script' => 'Latn', 'native' => 'bamanakan', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BM', null)],
        'jv'          => ['name' => 'Javanese (Latin)',       'script' => 'Latn', 'native' => 'Basa Jawa', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_JV', null)],
        'su'          => ['name' => 'Sundanese',              'script' => 'Latn', 'native' => 'Basa Sunda', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SU', null)],
        'bh'          => ['name' => 'Bihari',                 'script' => 'Latn', 'native' => 'Bihari', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BH', null)],
        'bi'          => ['name' => 'Bislama',                'script' => 'Latn', 'native' => 'Bislama', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BI', null)],
        'nb'          => ['name' => 'Norwegian Bokmål',       'script' => 'Latn', 'native' => 'Bokmål', 'regional' => 'nb_NO', 'domain' => env('LOCALIZATION_DOMAIN_NAME_NB', null)],
        'bs'          => ['name' => 'Bosnian',                'script' => 'Latn', 'native' => 'bosanski', 'regional' => 'bs_BA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BS', null)],
        'br'          => ['name' => 'Breton',                 'script' => 'Latn', 'native' => 'brezhoneg', 'regional' => 'br_FR', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BR', null)],
        'ca'          => ['name' => 'Catalan',                'script' => 'Latn', 'native' => 'català', 'regional' => 'ca_ES', 'domain' => env('LOCALIZATION_DOMAIN_NAME_CA', null)],
        'ch'          => ['name' => 'Chamorro',               'script' => 'Latn', 'native' => 'Chamoru', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_CH', null)],
        'ny'          => ['name' => 'Chewa',                  'script' => 'Latn', 'native' => 'chiCheŵa', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_NY', null)],
        'kde'         => ['name' => 'Makonde',                'script' => 'Latn', 'native' => 'Chimakonde', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KDE', null)],
        'sn'          => ['name' => 'Shona',                  'script' => 'Latn', 'native' => 'chiShona', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SN', null)],
        'co'          => ['name' => 'Corsican',               'script' => 'Latn', 'native' => 'corsu', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_CO', null)],
        'cy'          => ['name' => 'Welsh',                  'script' => 'Latn', 'native' => 'Cymraeg', 'regional' => 'cy_GB', 'domain' => env('LOCALIZATION_DOMAIN_NAME_CY', null)],
        'da'          => ['name' => 'Danish',                 'script' => 'Latn', 'native' => 'dansk', 'regional' => 'da_DK', 'domain' => env('LOCALIZATION_DOMAIN_NAME_DA', null)],
        'se'          => ['name' => 'Northern Sami',          'script' => 'Latn', 'native' => 'davvisámegiella', 'regional' => 'se_NO', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SE', null)],
        'de'          => ['name' => 'German',                 'script' => 'Latn', 'native' => 'Deutsch', 'regional' => 'de_DE', 'domain' => env('LOCALIZATION_DOMAIN_NAME_DE', null)],
        'luo'         => ['name' => 'Luo',                    'script' => 'Latn', 'native' => 'Dholuo', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_LUO', null)],
        'nv'          => ['name' => 'Navajo',                 'script' => 'Latn', 'native' => 'Diné bizaad', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_NV', null)],
        'dua'         => ['name' => 'Duala',                  'script' => 'Latn', 'native' => 'duálá', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_DUA', null)],
        'et'          => ['name' => 'Estonian',               'script' => 'Latn', 'native' => 'eesti', 'regional' => 'et_EE', 'domain' => env('LOCALIZATION_DOMAIN_NAME_ET', null)],
        'na'          => ['name' => 'Nauru',                  'script' => 'Latn', 'native' => 'Ekakairũ Naoero', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_NA', null)],
        'guz'         => ['name' => 'Ekegusii',               'script' => 'Latn', 'native' => 'Ekegusii', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_GUZ', null)],
        'en'          => ['name' => 'English',                'script' => 'Latn', 'native' => 'English', 'regional' => 'en_GB', 'domain' => env('LOCALIZATION_DOMAIN_NAME_EN', null)],
        'en-AU'       => ['name' => 'Australian English',     'script' => 'Latn', 'native' => 'Australian English', 'regional' => 'en_AU', 'domain' => env('LOCALIZATION_DOMAIN_NAME_EN_AU', null)],
        'en-GB'       => ['name' => 'British English',        'script' => 'Latn', 'native' => 'British English', 'regional' => 'en_GB', 'domain' => env('LOCALIZATION_DOMAIN_NAME_EN_GB', null)],
        'en-CA'       => ['name' => 'Canadian English',       'script' => 'Latn', 'native' => 'Canadian English', 'regional' => 'en_CA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_EN_CA', null)],
        'en-US'       => ['name' => 'U.S. English',           'script' => 'Latn', 'native' => 'U.S. English', 'regional' => 'en_US', 'domain' => env('LOCALIZATION_DOMAIN_NAME_EN_US', null)],
        'es'          => ['name' => 'Spanish',                'script' => 'Latn', 'native' => 'español', 'regional' => 'es_ES', 'domain' => env('LOCALIZATION_DOMAIN_NAME_ES', null)],
        'eo'          => ['name' => 'Esperanto',              'script' => 'Latn', 'native' => 'esperanto', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_EO', null)],
        'eu'          => ['name' => 'Basque',                 'script' => 'Latn', 'native' => 'euskara', 'regional' => 'eu_ES', 'domain' => env('LOCALIZATION_DOMAIN_NAME_EU', null)],
        'ewo'         => ['name' => 'Ewondo',                 'script' => 'Latn', 'native' => 'ewondo', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_EWO', null)],
        'ee'          => ['name' => 'Ewe',                    'script' => 'Latn', 'native' => 'eʋegbe', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_EE', null)],
        'fil'         => ['name' => 'Filipino',               'script' => 'Latn', 'native' => 'Filipino', 'regional' => 'fil_PH', 'domain' => env('LOCALIZATION_DOMAIN_NAME_FIL', null)],
        'fr'          => ['name' => 'French',                 'script' => 'Latn', 'native' => 'français', 'regional' => 'fr_FR', 'domain' => env('LOCALIZATION_DOMAIN_NAME_FR', null)],
        'fr-CA'       => ['name' => 'Canadian French',        'script' => 'Latn', 'native' => 'français canadien', 'regional' => 'fr_CA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_FR_CA', null)],
        'fy'          => ['name' => 'Western Frisian',        'script' => 'Latn', 'native' => 'frysk', 'regional' => 'fy_DE', 'domain' => env('LOCALIZATION_DOMAIN_NAME_FY', null)],
        'fur'         => ['name' => 'Friulian',               'script' => 'Latn', 'native' => 'furlan', 'regional' => 'fur_IT', 'domain' => env('LOCALIZATION_DOMAIN_NAME_FUR', null)],
        'fo'          => ['name' => 'Faroese',                'script' => 'Latn', 'native' => 'føroyskt', 'regional' => 'fo_FO', 'domain' => env('LOCALIZATION_DOMAIN_NAME_FO', null)],
        'gaa'         => ['name' => 'Ga',                     'script' => 'Latn', 'native' => 'Ga', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_GAA', null)],
        'ga'          => ['name' => 'Irish',                  'script' => 'Latn', 'native' => 'Gaeilge', 'regional' => 'ga_IE', 'domain' => env('LOCALIZATION_DOMAIN_NAME_GA', null)],
        'gv'          => ['name' => 'Manx',                   'script' => 'Latn', 'native' => 'Gaelg', 'regional' => 'gv_GB', 'domain' => env('LOCALIZATION_DOMAIN_NAME_GV', null)],
        'sm'          => ['name' => 'Samoan',                 'script' => 'Latn', 'native' => 'Gagana fa’a Sāmoa', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SM', null)],
        'gl'          => ['name' => 'Galician',               'script' => 'Latn', 'native' => 'galego', 'regional' => 'gl_ES', 'domain' => env('LOCALIZATION_DOMAIN_NAME_GL', null)],
        'ki'          => ['name' => 'Kikuyu',                 'script' => 'Latn', 'native' => 'Gikuyu', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KI', null)],
        'gd'          => ['name' => 'Scottish Gaelic',        'script' => 'Latn', 'native' => 'Gàidhlig', 'regional' => 'gd_GB', 'domain' => env('LOCALIZATION_DOMAIN_NAME_GD', null)],
        'ha'          => ['name' => 'Hausa',                  'script' => 'Latn', 'native' => 'Hausa', 'regional' => 'ha_NG', 'domain' => env('LOCALIZATION_DOMAIN_NAME_HA', null)],
        'bez'         => ['name' => 'Bena',                   'script' => 'Latn', 'native' => 'Hibena', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BEZ', null)],
        'ho'          => ['name' => 'Hiri Motu',              'script' => 'Latn', 'native' => 'Hiri Motu', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_HO', null)],
        'hr'          => ['name' => 'Croatian',               'script' => 'Latn', 'native' => 'hrvatski', 'regional' => 'hr_HR', 'domain' => env('LOCALIZATION_DOMAIN_NAME_HR', null)],
        'bem'         => ['name' => 'Bemba',                  'script' => 'Latn', 'native' => 'Ichibemba', 'regional' => 'bem_ZM', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BEM', null)],
        'io'          => ['name' => 'Ido',                    'script' => 'Latn', 'native' => 'Ido', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_IO', null)],
        'ig'          => ['name' => 'Igbo',                   'script' => 'Latn', 'native' => 'Igbo', 'regional' => 'ig_NG', 'domain' => env('LOCALIZATION_DOMAIN_NAME_IG', null)],
        'rn'          => ['name' => 'Rundi',                  'script' => 'Latn', 'native' => 'Ikirundi', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_RN', null)],
        'ia'          => ['name' => 'Interlingua',            'script' => 'Latn', 'native' => 'interlingua', 'regional' => 'ia_FR', 'domain' => env('LOCALIZATION_DOMAIN_NAME_IA', null)],
        'iu-Latn'     => ['name' => 'Inuktitut (Latin)',      'script' => 'Latn', 'native' => 'Inuktitut', 'regional' => 'iu_CA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_IU_LATN', null)],
        'sbp'         => ['name' => 'Sileibi',                'script' => 'Latn', 'native' => 'Ishisangu', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SPB', null)],
        'nd'          => ['name' => 'North Ndebele',          'script' => 'Latn', 'native' => 'isiNdebele', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_ND', null)],
        'nr'          => ['name' => 'South Ndebele',          'script' => 'Latn', 'native' => 'isiNdebele', 'regional' => 'nr_ZA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_NR', null)],
        'xh'          => ['name' => 'Xhosa',                  'script' => 'Latn', 'native' => 'isiXhosa', 'regional' => 'xh_ZA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_XH', null)],
        'zu'          => ['name' => 'Zulu',                   'script' => 'Latn', 'native' => 'isiZulu', 'regional' => 'zu_ZA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_ZU', null)],
        'it'          => ['name' => 'Italian',                'script' => 'Latn', 'native' => 'italiano', 'regional' => 'it_IT', 'domain' => env('LOCALIZATION_DOMAIN_NAME_IT', null)],
        'ik'          => ['name' => 'Inupiaq',                'script' => 'Latn', 'native' => 'Iñupiaq', 'regional' => 'ik_CA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_IK', null)],
        'dyo'         => ['name' => 'Jola-Fonyi',             'script' => 'Latn', 'native' => 'joola', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_DYO', null)],
        'kea'         => ['name' => 'Kabuverdianu',           'script' => 'Latn', 'native' => 'kabuverdianu', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KEA', null)],
        'kaj'         => ['name' => 'Jju',                    'script' => 'Latn', 'native' => 'Kaje', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KAJ', null)],
        'mh'          => ['name' => 'Marshallese',            'script' => 'Latn', 'native' => 'Kajin M̧ajeļ', 'regional' => 'mh_MH', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MH', null)],
        'kl'          => ['name' => 'Kalaallisut',            'script' => 'Latn', 'native' => 'kalaallisut', 'regional' => 'kl_GL', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KL', null)],
        'kln'         => ['name' => 'Kalenjin',               'script' => 'Latn', 'native' => 'Kalenjin', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KLN', null)],
        'kr'          => ['name' => 'Kanuri',                 'script' => 'Latn', 'native' => 'Kanuri', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KR', null)],
        'kcg'         => ['name' => 'Tyap',                   'script' => 'Latn', 'native' => 'Katab', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KCG', null)],
        'kw'          => ['name' => 'Cornish',                'script' => 'Latn', 'native' => 'kernewek', 'regional' => 'kw_GB', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KW', null)],
        'naq'         => ['name' => 'Nama',                   'script' => 'Latn', 'native' => 'Khoekhoegowab', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_NAQ', null)],
        'rof'         => ['name' => 'Rombo',                  'script' => 'Latn', 'native' => 'Kihorombo', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_ROF', null)],
        'kam'         => ['name' => 'Kamba',                  'script' => 'Latn', 'native' => 'Kikamba', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KAM', null)],
        'kg'          => ['name' => 'Kongo',                  'script' => 'Latn', 'native' => 'Kikongo', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KG', null)],
        'jmc'         => ['name' => 'Machame',                'script' => 'Latn', 'native' => 'Kimachame', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_JMC', null)],
        'rw'          => ['name' => 'Kinyarwanda',            'script' => 'Latn', 'native' => 'Kinyarwanda', 'regional' => 'rw_RW', 'domain' => env('LOCALIZATION_DOMAIN_NAME_RW', null)],
        'asa'         => ['name' => 'Kipare',                 'script' => 'Latn', 'native' => 'Kipare', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_ASA', null)],
        'rwk'         => ['name' => 'Rwa',                    'script' => 'Latn', 'native' => 'Kiruwa', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_RWK', null)],
        'saq'         => ['name' => 'Samburu',                'script' => 'Latn', 'native' => 'Kisampur', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SAQ', null)],
        'ksb'         => ['name' => 'Shambala',               'script' => 'Latn', 'native' => 'Kishambaa', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KSB', null)],
        'swc'         => ['name' => 'Congo Swahili',          'script' => 'Latn', 'native' => 'Kiswahili ya Kongo', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SWC', null)],
        'sw'          => ['name' => 'Swahili',                'script' => 'Latn', 'native' => 'Kiswahili', 'regional' => 'sw_KE', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SW', null)],
        'dav'         => ['name' => 'Dawida',                 'script' => 'Latn', 'native' => 'Kitaita', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_DAV', null)],
        'teo'         => ['name' => 'Teso',                   'script' => 'Latn', 'native' => 'Kiteso', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TEO', null)],
        'khq'         => ['name' => 'Koyra Chiini',           'script' => 'Latn', 'native' => 'Koyra ciini', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KHQ', null)],
        'ses'         => ['name' => 'Songhay',                'script' => 'Latn', 'native' => 'Koyraboro senni', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SES', null)],
        'mfe'         => ['name' => 'Morisyen',               'script' => 'Latn', 'native' => 'kreol morisien', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MFE', null)],
        'ht'          => ['name' => 'Haitian',                'script' => 'Latn', 'native' => 'Kreyòl ayisyen', 'regional' => 'ht_HT', 'domain' => env('LOCALIZATION_DOMAIN_NAME_HT', null)],
        'kj'          => ['name' => 'Kuanyama',               'script' => 'Latn', 'native' => 'Kwanyama', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KJ', null)],
        'ksh'         => ['name' => 'Kölsch',                 'script' => 'Latn', 'native' => 'Kölsch', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KSH', null)],
        'ebu'         => ['name' => 'Kiembu',                 'script' => 'Latn', 'native' => 'Kĩembu', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_EBU', null)],
        'mer'         => ['name' => 'Kimîîru',                'script' => 'Latn', 'native' => 'Kĩmĩrũ', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MER', null)],
        'lag'         => ['name' => 'Langi',                  'script' => 'Latn', 'native' => 'Kɨlaangi', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_LAG', null)],
        'lah'         => ['name' => 'Lahnda',                 'script' => 'Latn', 'native' => 'Lahnda', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_LAH', null)],
        'la'          => ['name' => 'Latin',                  'script' => 'Latn', 'native' => 'latine', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_LA', null)],
        'lv'          => ['name' => 'Latvian',                'script' => 'Latn', 'native' => 'latviešu', 'regional' => 'lv_LV', 'domain' => env('LOCALIZATION_DOMAIN_NAME_LV', null)],
        'to'          => ['name' => 'Tongan',                 'script' => 'Latn', 'native' => 'lea fakatonga', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TO', null)],
        'lt'          => ['name' => 'Lithuanian',             'script' => 'Latn', 'native' => 'lietuvių', 'regional' => 'lt_LT', 'domain' => env('LOCALIZATION_DOMAIN_NAME_LT', null)],
        'li'          => ['name' => 'Limburgish',             'script' => 'Latn', 'native' => 'Limburgs', 'regional' => 'li_BE', 'domain' => env('LOCALIZATION_DOMAIN_NAME_LI', null)],
        'ln'          => ['name' => 'Lingala',                'script' => 'Latn', 'native' => 'lingála', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_LN', null)],
        'lg'          => ['name' => 'Ganda',                  'script' => 'Latn', 'native' => 'Luganda', 'regional' => 'lg_UG', 'domain' => env('LOCALIZATION_DOMAIN_NAME_LG', null)],
        'luy'         => ['name' => 'Oluluyia',               'script' => 'Latn', 'native' => 'Luluhia', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_LUY', null)],
        'lb'          => ['name' => 'Luxembourgish',          'script' => 'Latn', 'native' => 'Lëtzebuergesch', 'regional' => 'lb_LU', 'domain' => env('LOCALIZATION_DOMAIN_NAME_LB', null)],
        'hu'          => ['name' => 'Hungarian',              'script' => 'Latn', 'native' => 'magyar', 'regional' => 'hu_HU', 'domain' => env('LOCALIZATION_DOMAIN_NAME_HU', null)],
        'mgh'         => ['name' => 'Makhuwa-Meetto',         'script' => 'Latn', 'native' => 'Makua', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MGH', null)],
        'mg'          => ['name' => 'Malagasy',               'script' => 'Latn', 'native' => 'Malagasy', 'regional' => 'mg_MG', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MG', null)],
        'mt'          => ['name' => 'Maltese',                'script' => 'Latn', 'native' => 'Malti', 'regional' => 'mt_MT', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MT', null)],
        'mtr'         => ['name' => 'Mewari',                 'script' => 'Latn', 'native' => 'Mewari', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MTR', null)],
        'mua'         => ['name' => 'Mundang',                'script' => 'Latn', 'native' => 'Mundang', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MUA', null)],
        'mi'          => ['name' => 'Māori',                  'script' => 'Latn', 'native' => 'Māori', 'regional' => 'mi_NZ', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MI', null)],
        'nl'          => ['name' => 'Dutch',                  'script' => 'Latn', 'native' => 'Nederlands', 'regional' => 'nl_NL', 'domain' => env('LOCALIZATION_DOMAIN_NAME_NL', null)],
        'nmg'         => ['name' => 'Kwasio',                 'script' => 'Latn', 'native' => 'ngumba', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_NMG', null)],
        'yav'         => ['name' => 'Yangben',                'script' => 'Latn', 'native' => 'nuasue', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_YAV', null)],
        'nn'          => ['name' => 'Norwegian Nynorsk',      'script' => 'Latn', 'native' => 'nynorsk', 'regional' => 'nn_NO', 'domain' => env('LOCALIZATION_DOMAIN_NAME_NN', null)],
        'oc'          => ['name' => 'Occitan',                'script' => 'Latn', 'native' => 'occitan', 'regional' => 'oc_FR', 'domain' => env('LOCALIZATION_DOMAIN_NAME_OC', null)],
        'ang'         => ['name' => 'Old English',            'script' => 'Runr', 'native' => 'Old English', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_ANG', null)],
        'xog'         => ['name' => 'Soga',                   'script' => 'Latn', 'native' => 'Olusoga', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_XOG', null)],
        'om'          => ['name' => 'Oromo',                  'script' => 'Latn', 'native' => 'Oromoo', 'regional' => 'om_ET', 'domain' => env('LOCALIZATION_DOMAIN_NAME_OM', null)],
        'ng'          => ['name' => 'Ndonga',                 'script' => 'Latn', 'native' => 'OshiNdonga', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_NG', null)],
        'hz'          => ['name' => 'Herero',                 'script' => 'Latn', 'native' => 'Otjiherero', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_HZ', null)],
        'uz-Latn'     => ['name' => 'Uzbek (Latin)',          'script' => 'Latn', 'native' => 'oʼzbekcha', 'regional' => 'uz_UZ', 'domain' => env('LOCALIZATION_DOMAIN_NAME_UZ_LATN', null)],
        'nds'         => ['name' => 'Low German',             'script' => 'Latn', 'native' => 'Plattdüütsch', 'regional' => 'nds_DE', 'domain' => env('LOCALIZATION_DOMAIN_NAME_NDS', null)],
        'pl'          => ['name' => 'Polish',                 'script' => 'Latn', 'native' => 'polski', 'regional' => 'pl_PL', 'domain' => env('LOCALIZATION_DOMAIN_NAME_PL', null)],
        'pt'          => ['name' => 'Portuguese',             'script' => 'Latn', 'native' => 'português', 'regional' => 'pt_PT', 'domain' => env('LOCALIZATION_DOMAIN_NAME_PT', null)],
        'pt-BR'       => ['name' => 'Brazilian Portuguese',   'script' => 'Latn', 'native' => 'português do Brasil', 'regional' => 'pt_BR', 'domain' => env('LOCALIZATION_DOMAIN_NAME_PT_BR', null)],
        'ff'          => ['name' => 'Fulah',                  'script' => 'Latn', 'native' => 'Pulaar', 'regional' => 'ff_SN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_FF', null)],
        'pi'          => ['name' => 'Pahari-Potwari',         'script' => 'Latn', 'native' => 'Pāli', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_PI', null)],
        'aa'          => ['name' => 'Afar',                   'script' => 'Latn', 'native' => 'Qafar', 'regional' => 'aa_ER', 'domain' => env('LOCALIZATION_DOMAIN_NAME_AA', null)],
        'ty'          => ['name' => 'Tahitian',               'script' => 'Latn', 'native' => 'Reo Māohi', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TY', null)],
        'ksf'         => ['name' => 'Bafia',                  'script' => 'Latn', 'native' => 'rikpa', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KSF', null)],
        'ro'          => ['name' => 'Romanian',               'script' => 'Latn', 'native' => 'română', 'regional' => 'ro_RO', 'domain' => env('LOCALIZATION_DOMAIN_NAME_RO', null)],
        'cgg'         => ['name' => 'Chiga',                  'script' => 'Latn', 'native' => 'Rukiga', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_CGG', null)],
        'rm'          => ['name' => 'Romansh',                'script' => 'Latn', 'native' => 'rumantsch', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_RM', null)],
        'qu'          => ['name' => 'Quechua',                'script' => 'Latn', 'native' => 'Runa Simi', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_QU', null)],
        'nyn'         => ['name' => 'Nyankole',               'script' => 'Latn', 'native' => 'Runyankore', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_NYN', null)],
        'ssy'         => ['name' => 'Saho',                   'script' => 'Latn', 'native' => 'Saho', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SSY', null)],
        'sc'          => ['name' => 'Sardinian',              'script' => 'Latn', 'native' => 'sardu', 'regional' => 'sc_IT', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SC', null)],
        'de-CH'       => ['name' => 'Swiss High German',      'script' => 'Latn', 'native' => 'Schweizer Hochdeutsch', 'regional' => 'de_CH', 'domain' => env('LOCALIZATION_DOMAIN_NAME_DE_CH', null)],
        'gsw'         => ['name' => 'Swiss German',           'script' => 'Latn', 'native' => 'Schwiizertüütsch', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_GSW', null)],
        'trv'         => ['name' => 'Taroko',                 'script' => 'Latn', 'native' => 'Seediq', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TRV', null)],
        'seh'         => ['name' => 'Sena',                   'script' => 'Latn', 'native' => 'sena', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SEH', null)],
        'nso'         => ['name' => 'Northern Sotho',         'script' => 'Latn', 'native' => 'Sesotho sa Leboa', 'regional' => 'nso_ZA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_NSO', null)],
        'st'          => ['name' => 'Southern Sotho',         'script' => 'Latn', 'native' => 'Sesotho', 'regional' => 'st_ZA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_ST', null)],
        'tn'          => ['name' => 'Tswana',                 'script' => 'Latn', 'native' => 'Setswana', 'regional' => 'tn_ZA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TN', null)],
        'sq'          => ['name' => 'Albanian',               'script' => 'Latn', 'native' => 'shqip', 'regional' => 'sq_AL', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SQ', null)],
        'sid'         => ['name' => 'Sidamo',                 'script' => 'Latn', 'native' => 'Sidaamu Afo', 'regional' => 'sid_ET', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SID', null)],
        'ss'          => ['name' => 'Swati',                  'script' => 'Latn', 'native' => 'Siswati', 'regional' => 'ss_ZA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SS', null)],
        'sk'          => ['name' => 'Slovak',                 'script' => 'Latn', 'native' => 'slovenčina', 'regional' => 'sk_SK', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SK', null)],
        'sl'          => ['name' => 'Slovene',                'script' => 'Latn', 'native' => 'slovenščina', 'regional' => 'sl_SI', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SL', null)],
        'so'          => ['name' => 'Somali',                 'script' => 'Latn', 'native' => 'Soomaali', 'regional' => 'so_SO', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SO', null)],
        'sr-Latn'     => ['name' => 'Serbian (Latin)',        'script' => 'Latn', 'native' => 'Srpski', 'regional' => 'sr_RS', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SR_LATN', null)],
        'sh'          => ['name' => 'Serbo-Croatian',         'script' => 'Latn', 'native' => 'srpskohrvatski', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SH', null)],
        'fi'          => ['name' => 'Finnish',                'script' => 'Latn', 'native' => 'suomi', 'regional' => 'fi_FI', 'domain' => env('LOCALIZATION_DOMAIN_NAME_FI', null)],
        'sv'          => ['name' => 'Swedish',                'script' => 'Latn', 'native' => 'svenska', 'regional' => 'sv_SE', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SV', null)],
        'sg'          => ['name' => 'Sango',                  'script' => 'Latn', 'native' => 'Sängö', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SG', null)],
        'tl'          => ['name' => 'Tagalog',                'script' => 'Latn', 'native' => 'Tagalog', 'regional' => 'tl_PH', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TL', null)],
        'tzm-Latn'    => ['name' => 'Central Atlas Tamazight (Latin)', 'script' => 'Latn', 'native' => 'Tamazight', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TZM_LATN', null)],
        'kab'         => ['name' => 'Kabyle',                 'script' => 'Latn', 'native' => 'Taqbaylit', 'regional' => 'kab_DZ', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KAB', null)],
        'twq'         => ['name' => 'Tasawaq',                'script' => 'Latn', 'native' => 'Tasawaq senni', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TWQ', null)],
        'shi'         => ['name' => 'Tachelhit (Latin)',      'script' => 'Latn', 'native' => 'Tashelhit', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SHI', null)],
        'nus'         => ['name' => 'Nuer',                   'script' => 'Latn', 'native' => 'Thok Nath', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_NUS', null)],
        'vi'          => ['name' => 'Vietnamese',             'script' => 'Latn', 'native' => 'Tiếng Việt', 'regional' => 'vi_VN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_VI', null)],
        'tg-Latn'     => ['name' => 'Tajik (Latin)',          'script' => 'Latn', 'native' => 'tojikī', 'regional' => 'tg_TJ', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TG_LATN', null)],
        'lu'          => ['name' => 'Luba-Katanga',           'script' => 'Latn', 'native' => 'Tshiluba', 'regional' => 've_ZA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_LU', null)],
        've'          => ['name' => 'Venda',                  'script' => 'Latn', 'native' => 'Tshivenḓa', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_VE', null)],
        'tw'          => ['name' => 'Twi',                    'script' => 'Latn', 'native' => 'Twi', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TW', null)],
        'tr'          => ['name' => 'Turkish',                'script' => 'Latn', 'native' => 'Türkçe', 'regional' => 'tr_TR', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TR', null)],
        'ale'         => ['name' => 'Aleut',                  'script' => 'Latn', 'native' => 'Unangax tunuu', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_ALE', null)],
        'ca-valencia' => ['name' => 'Valencian',              'script' => 'Latn', 'native' => 'valencià', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_CA_VALENCIA', null)],
        'vai-Latn'    => ['name' => 'Vai (Latin)',            'script' => 'Latn', 'native' => 'Viyamíĩ', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_VAI_LATN', null)],
        'vo'          => ['name' => 'Volapük',                'script' => 'Latn', 'native' => 'Volapük', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_VO', null)],
        'fj'          => ['name' => 'Fijian',                 'script' => 'Latn', 'native' => 'vosa Vakaviti', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_FJ', null)],
        'wa'          => ['name' => 'Walloon',                'script' => 'Latn', 'native' => 'Walon', 'regional' => 'wa_BE', 'domain' => env('LOCALIZATION_DOMAIN_NAME_WA', null)],
        'wae'         => ['name' => 'Walser',                 'script' => 'Latn', 'native' => 'Walser', 'regional' => 'wae_CH', 'domain' => env('LOCALIZATION_DOMAIN_NAME_WAE', null)],
        'wen'         => ['name' => 'Sorbian',                'script' => 'Latn', 'native' => 'Wendic', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_WEN', null)],
        'wo'          => ['name' => 'Wolof',                  'script' => 'Latn', 'native' => 'Wolof', 'regional' => 'wo_SN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_WO', null)],
        'ts'          => ['name' => 'Tsonga',                 'script' => 'Latn', 'native' => 'Xitsonga', 'regional' => 'ts_ZA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TS', null)],
        'dje'         => ['name' => 'Zarma',                  'script' => 'Latn', 'native' => 'Zarmaciine', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_DJE', null)],
        'yo'          => ['name' => 'Yoruba',                 'script' => 'Latn', 'native' => 'Èdè Yorùbá', 'regional' => 'yo_NG', 'domain' => env('LOCALIZATION_DOMAIN_NAME_YO', null)],
        'de-AT'       => ['name' => 'Austrian German',        'script' => 'Latn', 'native' => 'Österreichisches Deutsch', 'regional' => 'de_AT', 'domain' => env('LOCALIZATION_DOMAIN_NAME_DE_AT', null)],
        'is'          => ['name' => 'Icelandic',              'script' => 'Latn', 'native' => 'íslenska', 'regional' => 'is_IS', 'domain' => env('LOCALIZATION_DOMAIN_NAME_IS', null)],
        'cs'          => ['name' => 'Czech',                  'script' => 'Latn', 'native' => 'čeština', 'regional' => 'cs_CZ', 'domain' => env('LOCALIZATION_DOMAIN_NAME_CS', null)],
        'bas'         => ['name' => 'Basa',                   'script' => 'Latn', 'native' => 'Ɓàsàa', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BAS', null)],
        'mas'         => ['name' => 'Masai',                  'script' => 'Latn', 'native' => 'ɔl-Maa', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MAS', null)],
        'haw'         => ['name' => 'Hawaiian',               'script' => 'Latn', 'native' => 'ʻŌlelo Hawaiʻi', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_HAW', null)],
        'el'          => ['name' => 'Greek',                  'script' => 'Grek', 'native' => 'Ελληνικά', 'regional' => 'el_GR', 'domain' => env('LOCALIZATION_DOMAIN_NAME_EL', null)],
        'uz'          => ['name' => 'Uzbek (Cyrillic)',       'script' => 'Cyrl', 'native' => 'Ўзбек', 'regional' => 'uz_UZ', 'domain' => env('LOCALIZATION_DOMAIN_NAME_UZ', null)],
        'az-Cyrl'     => ['name' => 'Azerbaijani (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Азәрбајҹан', 'regional' => 'uz_UZ', 'domain' => env('LOCALIZATION_DOMAIN_NAME_AZ_CYRL', null)],
        'ab'          => ['name' => 'Abkhazian',              'script' => 'Cyrl', 'native' => 'Аҧсуа', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_AB', null)],
        'os'          => ['name' => 'Ossetic',                'script' => 'Cyrl', 'native' => 'Ирон', 'regional' => 'os_RU', 'domain' => env('LOCALIZATION_DOMAIN_NAME_OS', null)],
        'ky'          => ['name' => 'Kyrgyz',                 'script' => 'Cyrl', 'native' => 'Кыргыз', 'regional' => 'ky_KG', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KY', null)],
        'sr'          => ['name' => 'Serbian (Cyrillic)',     'script' => 'Cyrl', 'native' => 'Српски', 'regional' => 'sr_RS', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SR', null)],
        'av'          => ['name' => 'Avaric',                 'script' => 'Cyrl', 'native' => 'авар мацӀ', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_AV', null)],
        'ady'         => ['name' => 'Adyghe',                 'script' => 'Cyrl', 'native' => 'адыгэбзэ', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_ADY', null)],
        'ba'          => ['name' => 'Bashkir',                'script' => 'Cyrl', 'native' => 'башҡорт теле', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BA', null)],
        'be'          => ['name' => 'Belarusian',             'script' => 'Cyrl', 'native' => 'беларуская', 'regional' => 'be_BY', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BE', null)],
        'bg'          => ['name' => 'Bulgarian',              'script' => 'Cyrl', 'native' => 'български', 'regional' => 'bg_BG', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BG', null)],
        'kv'          => ['name' => 'Komi',                   'script' => 'Cyrl', 'native' => 'коми кыв', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KV', null)],
        'mk'          => ['name' => 'Macedonian',             'script' => 'Cyrl', 'native' => 'македонски', 'regional' => 'mk_MK', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MK', null)],
        'mn'          => ['name' => 'Mongolian (Cyrillic)',   'script' => 'Cyrl', 'native' => 'монгол', 'regional' => 'mn_MN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MN', null)],
        'ce'          => ['name' => 'Chechen',                'script' => 'Cyrl', 'native' => 'нохчийн мотт', 'regional' => 'ce_RU', 'domain' => env('LOCALIZATION_DOMAIN_NAME_CE', null)],
        'ru'          => ['name' => 'Russian',                'script' => 'Cyrl', 'native' => 'русский', 'regional' => 'ru_RU', 'domain' => env('LOCALIZATION_DOMAIN_NAME_RU', null)],
        'sah'         => ['name' => 'Yakut',                  'script' => 'Cyrl', 'native' => 'саха тыла', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SAH', null)],
        'tt'          => ['name' => 'Tatar',                  'script' => 'Cyrl', 'native' => 'татар теле', 'regional' => 'tt_RU', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TT', null)],
        'tg'          => ['name' => 'Tajik (Cyrillic)',       'script' => 'Cyrl', 'native' => 'тоҷикӣ', 'regional' => 'tg_TJ', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TG', null)],
        'tk'          => ['name' => 'Turkmen',                'script' => 'Cyrl', 'native' => 'түркменче', 'regional' => 'tk_TM', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TK', null)],
        'uk'          => ['name' => 'Ukrainian',              'script' => 'Cyrl', 'native' => 'українська', 'regional' => 'uk_UA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_UK', null)],
        'cv'          => ['name' => 'Chuvash',                'script' => 'Cyrl', 'native' => 'чӑваш чӗлхи', 'regional' => 'cv_RU', 'domain' => env('LOCALIZATION_DOMAIN_NAME_CV', null)],
        'cu'          => ['name' => 'Church Slavic',          'script' => 'Cyrl', 'native' => 'ѩзыкъ словѣньскъ', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_CU', null)],
        'kk'          => ['name' => 'Kazakh',                 'script' => 'Cyrl', 'native' => 'қазақ тілі', 'regional' => 'kk_KZ', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KK', null)],
        'hy'          => ['name' => 'Armenian',               'script' => 'Armn', 'native' => 'Հայերեն', 'regional' => 'hy_AM', 'domain' => env('LOCALIZATION_DOMAIN_NAME_HY', null)],
        'yi'          => ['name' => 'Yiddish',                'script' => 'Hebr', 'native' => 'ייִדיש', 'regional' => 'yi_US', 'domain' => env('LOCALIZATION_DOMAIN_NAME_YI', null)],
        'he'          => ['name' => 'Hebrew',                 'script' => 'Hebr', 'native' => 'עברית', 'regional' => 'he_IL', 'domain' => env('LOCALIZATION_DOMAIN_NAME_HE', null)],
        'ug'          => ['name' => 'Uyghur',                 'script' => 'Arab', 'native' => 'ئۇيغۇرچە', 'regional' => 'ug_CN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_UG', null)],
        'ur'          => ['name' => 'Urdu',                   'script' => 'Arab', 'native' => 'اردو', 'regional' => 'ur_PK', 'domain' => env('LOCALIZATION_DOMAIN_NAME_UR', null)],
        'ar'          => ['name' => 'Arabic',                 'script' => 'Arab', 'native' => 'العربية', 'regional' => 'ar_AE', 'domain' => env('LOCALIZATION_DOMAIN_NAME_AR', null)],
        'uz-Arab'     => ['name' => 'Uzbek (Arabic)',         'script' => 'Arab', 'native' => 'اۉزبېک', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_UZ_ARAB', null)],
        'tg-Arab'     => ['name' => 'Tajik (Arabic)',         'script' => 'Arab', 'native' => 'تاجیکی', 'regional' => 'tg_TJ', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TG_ARAB', null)],
        'sd'          => ['name' => 'Sindhi',                 'script' => 'Arab', 'native' => 'سنڌي', 'regional' => 'sd_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SD', null)],
        'fa'          => ['name' => 'Persian',                'script' => 'Arab', 'native' => 'فارسی', 'regional' => 'fa_IR', 'domain' => env('LOCALIZATION_DOMAIN_NAME_FA', null)],
        'pa-Arab'     => ['name' => 'Punjabi (Arabic)',       'script' => 'Arab', 'native' => 'پنجاب', 'regional' => 'pa_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_PA_ARAB', null)],
        'ps'          => ['name' => 'Pashto',                 'script' => 'Arab', 'native' => 'پښتو', 'regional' => 'ps_AF', 'domain' => env('LOCALIZATION_DOMAIN_NAME_PS', null)],
        'ks'          => ['name' => 'Kashmiri (Arabic)',      'script' => 'Arab', 'native' => 'کأشُر', 'regional' => 'ks_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KS', null)],
        'ku'          => ['name' => 'Kurdish',                'script' => 'Arab', 'native' => 'کوردی', 'regional' => 'ku_TR', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KU', null)],
        'dv'          => ['name' => 'Divehi',                 'script' => 'Thaa', 'native' => 'ދިވެހިބަސް', 'regional' => 'dv_MV', 'domain' => env('LOCALIZATION_DOMAIN_NAME_DV', null)],
        'ks-Deva'     => ['name' => 'Kashmiri (Devaganari)',  'script' => 'Deva', 'native' => 'कॉशुर', 'regional' => 'ks_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KS_DEVA', null)],
        'kok'         => ['name' => 'Konkani',                'script' => 'Deva', 'native' => 'कोंकणी', 'regional' => 'kok_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KOK', null)],
        'doi'         => ['name' => 'Dogri',                  'script' => 'Deva', 'native' => 'डोगरी', 'regional' => 'doi_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_DOI', null)],
        'ne'          => ['name' => 'Nepali',                 'script' => 'Deva', 'native' => 'नेपाली', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_NE', null)],
        'pra'         => ['name' => 'Prakrit',                'script' => 'Deva', 'native' => 'प्राकृत', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_PRA', null)],
        'brx'         => ['name' => 'Bodo',                   'script' => 'Deva', 'native' => 'बड़ो', 'regional' => 'brx_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BRX', null)],
        'bra'         => ['name' => 'Braj',                   'script' => 'Deva', 'native' => 'ब्रज भाषा', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BRA', null)],
        'mr'          => ['name' => 'Marathi',                'script' => 'Deva', 'native' => 'मराठी', 'regional' => 'mr_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MR', null)],
        'mai'         => ['name' => 'Maithili',               'script' => 'Tirh', 'native' => 'मैथिली', 'regional' => 'mai_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MAI', null)],
        'raj'         => ['name' => 'Rajasthani',             'script' => 'Deva', 'native' => 'राजस्थानी', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_RAJ', null)],
        'sa'          => ['name' => 'Sanskrit',               'script' => 'Deva', 'native' => 'संस्कृतम्', 'regional' => 'sa_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SA', null)],
        'hi'          => ['name' => 'Hindi',                  'script' => 'Deva', 'native' => 'हिन्दी', 'regional' => 'hi_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_HI', null)],
        'as'          => ['name' => 'Assamese',               'script' => 'Beng', 'native' => 'অসমীয়া', 'regional' => 'as_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_AS', null)],
        'bn'          => ['name' => 'Bengali',                'script' => 'Beng', 'native' => 'বাংলা', 'regional' => 'bn_BD', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BN', null)],
        'mni'         => ['name' => 'Manipuri',               'script' => 'Beng', 'native' => 'মৈতৈ', 'regional' => 'mni_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MNI', null)],
        'pa'          => ['name' => 'Punjabi (Gurmukhi)',     'script' => 'Guru', 'native' => 'ਪੰਜਾਬੀ', 'regional' => 'pa_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_PA', null)],
        'gu'          => ['name' => 'Gujarati',               'script' => 'Gujr', 'native' => 'ગુજરાતી', 'regional' => 'gu_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_GU', null)],
        'or'          => ['name' => 'Oriya',                  'script' => 'Orya', 'native' => 'ଓଡ଼ିଆ', 'regional' => 'or_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_OR', null)],
        'ta'          => ['name' => 'Tamil',                  'script' => 'Taml', 'native' => 'தமிழ்', 'regional' => 'ta_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TA', null)],
        'te'          => ['name' => 'Telugu',                 'script' => 'Telu', 'native' => 'తెలుగు', 'regional' => 'te_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TE', null)],
        'kn'          => ['name' => 'Kannada',                'script' => 'Knda', 'native' => 'ಕನ್ನಡ', 'regional' => 'kn_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KN', null)],
        'ml'          => ['name' => 'Malayalam',              'script' => 'Mlym', 'native' => 'മലയാളം', 'regional' => 'ml_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_ML', null)],
        'si'          => ['name' => 'Sinhala',                'script' => 'Sinh', 'native' => 'සිංහල', 'regional' => 'si_LK', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SI', null)],
        'th'          => ['name' => 'Thai',                   'script' => 'Thai', 'native' => 'ไทย', 'regional' => 'th_TH', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TH', null)],
        'lo'          => ['name' => 'Lao',                    'script' => 'Laoo', 'native' => 'ລາວ', 'regional' => 'lo_LA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_LO', null)],
        'bo'          => ['name' => 'Tibetan',                'script' => 'Tibt', 'native' => 'པོད་སྐད་', 'regional' => 'bo_IN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BO', null)],
        'dz'          => ['name' => 'Dzongkha',               'script' => 'Tibt', 'native' => 'རྫོང་ཁ', 'regional' => 'dz_BT', 'domain' => env('LOCALIZATION_DOMAIN_NAME_DZ', null)],
        'my'          => ['name' => 'Burmese',                'script' => 'Mymr', 'native' => 'မြန်မာဘာသာ', 'regional' => 'my_MM', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MY', null)],
        'ka'          => ['name' => 'Georgian',               'script' => 'Geor', 'native' => 'ქართული', 'regional' => 'ka_GE', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KA', null)],
        'byn'         => ['name' => 'Blin',                   'script' => 'Ethi', 'native' => 'ብሊን', 'regional' => 'byn_ER', 'domain' => env('LOCALIZATION_DOMAIN_NAME_BYN', null)],
        'tig'         => ['name' => 'Tigre',                  'script' => 'Ethi', 'native' => 'ትግረ', 'regional' => 'tig_ER', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TIG', null)],
        'ti'          => ['name' => 'Tigrinya',               'script' => 'Ethi', 'native' => 'ትግርኛ', 'regional' => 'ti_ET', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TI', null)],
        'am'          => ['name' => 'Amharic',                'script' => 'Ethi', 'native' => 'አማርኛ', 'regional' => 'am_ET', 'domain' => env('LOCALIZATION_DOMAIN_NAME_AM', null)],
        'wal'         => ['name' => 'Wolaytta',               'script' => 'Ethi', 'native' => 'ወላይታቱ', 'regional' => 'wal_ET', 'domain' => env('LOCALIZATION_DOMAIN_NAME_WAL', null)],
        'chr'         => ['name' => 'Cherokee',               'script' => 'Cher', 'native' => 'ᏣᎳᎩ', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_CHR', null)],
        'iu'          => ['name' => 'Inuktitut (Canadian Aboriginal Syllabics)', 'script' => 'Cans', 'native' => 'ᐃᓄᒃᑎᑐᑦ', 'regional' => 'iu_CA', 'domain' => env('LOCALIZATION_DOMAIN_NAME_IU', null)],
        'oj'          => ['name' => 'Ojibwa',                 'script' => 'Cans', 'native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_OJ', null)],
        'cr'          => ['name' => 'Cree',                   'script' => 'Cans', 'native' => 'ᓀᐦᐃᔭᐍᐏᐣ', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_CR', null)],
        'km'          => ['name' => 'Khmer',                  'script' => 'Khmr', 'native' => 'ភាសាខ្មែរ', 'regional' => 'km_KH', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KM', null)],
        'mn-Mong'     => ['name' => 'Mongolian (Mongolian)',  'script' => 'Mong', 'native' => 'ᠮᠣᠨᠭᠭᠣᠯ ᠬᠡᠯᠡ', 'regional' => 'mn_MN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_MN_MONG', null)],
        'shi-Tfng'    => ['name' => 'Tachelhit (Tifinagh)',   'script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_SHI_TFNG', null)],
        'tzm'         => ['name' => 'Central Atlas Tamazight (Tifinagh)','script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_TZM', null)],
        'yue'         => ['name' => 'Yue',                    'script' => 'Hant', 'native' => '廣州話', 'regional' => 'yue_HK', 'domain' => env('LOCALIZATION_DOMAIN_NAME_YUE', null)],
        'ja'          => ['name' => 'Japanese',               'script' => 'Jpan', 'native' => '日本語', 'regional' => 'ja_JP', 'domain' => env('LOCALIZATION_DOMAIN_NAME_JA', null)],
        'zh'          => ['name' => 'Chinese (Simplified)',   'script' => 'Hans', 'native' => '简体中文', 'regional' => 'zh_CN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_ZH', null)],
        'zh-Hant'     => ['name' => 'Chinese (Traditional)',  'script' => 'Hant', 'native' => '繁體中文', 'regional' => 'zh_CN', 'domain' => env('LOCALIZATION_DOMAIN_NAME_ZH_HANT', null)],
        'ii'          => ['name' => 'Sichuan Yi',             'script' => 'Yiii', 'native' => 'ꆈꌠꉙ', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_II', null)],
        'vai'         => ['name' => 'Vai (Vai)',              'script' => 'Vaii', 'native' => 'ꕙꔤ', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_VAI', null)],
        'jv-Java'     => ['name' => 'Javanese (Javanese)',    'script' => 'Java', 'native' => 'ꦧꦱꦗꦮ', 'regional' => '', 'domain' => env('LOCALIZATION_DOMAIN_NAME_JV_JAVA', null)],
        'ko'          => ['name' => 'Korean',                 'script' => 'Hang', 'native' => '한국어', 'regional' => 'ko_KR', 'domain' => env('LOCALIZATION_DOMAIN_NAME_KO', null)],
    ],

    // Negotiate for the user locale using the Accept-Language header if it's not defined in the URL?
    // If false, system will take app.php locale attribute
    'useAcceptLanguageHeader' => true,

    // If LaravelLocalizationRedirectFilter is active and hideDefaultLocaleInURL
    // is true, the url would not have the default application language
    //
    // IMPORTANT - When hideDefaultLocaleInURL is set to true, the unlocalized root is treated as the applications default locale "app.locale".
    // Because of this language negotiation using the Accept-Language header will NEVER occur when hideDefaultLocaleInURL is true.
    //
    'hideDefaultLocaleInURL' => false,

    // If you want to display the locales in particular order in the language selector you should write the order here.
    //CAUTION: Please consider using the appropriate locale code otherwise it will not work
    //Example: 'localesOrder' => ['es','en'],
    'localesOrder' => [],

    //  If you want to use custom lang url segments like 'at' instead of 'de-AT', you can use the mapping to tallow the LanguageNegotiator to assign the descired locales based on HTTP Accept Language Header. For example you want ot use 'at', so map HTTP Accept Language Header 'de-AT' to 'at' (['de-AT' => 'at']).
    'localesMapping' => [],

    // URLs which should not be processed, e.g. '/nova', '/nova/*', '/nova-api/*' or specific application URLs
    // Defaults to []
    'urlsIgnored' => [],
];
